### ISSUE TITLE
exp_main.py的163行多传入了batch_y

### ISSUE THREAD

**Issue by nnstake** [cure-lab/LTSF-Linear#101]

**Comment by nnstake** [comment]
我看了informer和autoformer的代码是没有的，而且我觉得也是不合理的，是笔误还是有什么特殊含义。

**Comment by mixiancmx** [comment]
诶不是笔误，他们的代码后来把这个batch_y改了，我们写的时候是参照他们很早期的代码。不过那个不会有数据泄露，实际上提供的内容还是batch_x中的
