### ISSUE TITLE
Comparision with #Quatformer#?

### ISSUE THREAD

**Issue by crazydogen** [cure-lab/LTSF-Linear#17]
Hi there,
I would like to know if it is possible to add Quatformer to the comparison list.
BTW awesome work.

_Quatformer Ref:_
https://dl.acm.org/doi/abs/10.1145/3534678.3539234

**Comment by mixiancmx** [comment]
Hi, the performance of Quatformer seems not better than FEDformer. Therefore we didn't add it to the comparison list. We might conclude that paper in the future.
