### ISSUE TITLE
Question regarding training with just pos embeddings

### ISSUE THREAD

**Issue by Vaiyani** [cure-lab/LTSF-Linear#19]
Hi, 

Thank you for this insightful paper and the code base. I had a question:

Q1) I want to train the model (Transformer) with just pos embedding (as the original Transformer with just positional embedding dependent on trigonometric function), no value or temporal embedding. It throws an error because of different tensor sizes. Should we add an nn.linear embedding of output d_model before pos embedding to make the tensor size consistent? Does this seem consistent or do we have a more robust way?

**Comment by mixiancmx** [comment]
Hi, you can use "DataEmbedding_wo_temp" by setting args.embed_type to 3. The value embedding must be used, it is relative to the input(the look-back window). If you don't use value embedding, the input value is not given to the transformer's encoder and decoder. If you really want to use positional embedding only, you can directly change the size of the tensor by repeating its value.
Sorry to reply so late.

**Comment by Vaiyani** [comment]
Right, I get your point regarding pos embedding to repeat the value over the entire batch size.

and as far as I understand the "value embedding" (Token embeddings) is used to expand the dimension of the datapoints with convolution (c_in to d_model) to make it compatible with the other embeddings. like in this case pos embeddings.

**Comment by mixiancmx** [comment]
Yes, you can also use the (positional embedding + raw input). If you don't want to use the value embedding. In this case, you need to set the value of argument  "d_model" to the same value as "enc_in".

**Comment by Vaiyani** [comment]
Perfect. Thanks
