### ISSUE TITLE
How to understand the test result CORR?

### ISSUE THREAD

**Issue by Zero-coder** [cure-lab/LTSF-Linear#20]
Thank you so much for such insight on tsf tasks!!!
I have a simple question,Given dataset ettm1 for example,how to understand the Corr?the shape of Corr is correlated with the shape of datasets? example ,input shape (8,7,96),output shape (8,7,96)

**Comment by Zero-coder** [comment]
def CORR(pred, true):
    u = ((true - true.mean(0)) * (pred - pred.mean(0))).sum(0)
    d = np.sqrt(((true - true.mean(0)) ** 2 * (pred - pred.mean(0)) ** 2).sum(0))
    d += 1e-12
    return 0.01*(u / d).mean(-1)

**Comment by Zero-coder** [comment]
corr:[0.47574195 0.47565466 0.47556144 0.47549233 0.47544628 0.47540995
 0.47535673 0.47530493 0.4752553  0.47520882 0.4751605  0.47513056
 0.4750887  0.4750482  0.4750311  0.47500446 0.47496623 0.47495672
 0.4749462  0.4749406  0.4749572  0.4749815  0.47501782 0.4750318
 0.47506145 0.4750973  0.4751471  0.4751999  0.4752628  0.47533262
 0.47540802 0.47547504 0.47554046 0.4755973  0.47562975 0.47565216
 0.47567737 0.47572654 0.4757779  0.47584084 0.47583777 0.4758759
 0.4758733  0.4758813  0.47590122 0.47591865 0.47595203 0.47602108
 0.4760946  0.4761316  0.47616473 0.4761973  0.4762586  0.47628883
 0.47633553 0.47633487 0.47635004 0.47636804 0.47638464 0.47639233
 0.47639832 0.47639942 0.47638786 0.47638342 0.47639117 0.476421
 0.476459   0.47650754 0.47656578 0.476616   0.4766691  0.47673216
 0.4768134  0.47690815 0.47700286 0.4770986  0.4771905  0.47728816
 0.47737902 0.4774702  0.47755668 0.4776473  0.47773287 0.47780854
 0.47788683 0.4779493  0.4780248  0.47809124 0.47815788 0.47822165
 0.47831705 0.47840124 0.4784808  0.47857422 0.47867918 0.47881743]

**Comment by mixiancmx** [comment]
This function is from Informer's repository. You can refer to the function CORR in `utils/metrics.py`. It is the Pearson Correlation of predicted value and true value.
<img width="819" alt="image" src="https://user-images.githubusercontent.com/83197963/193443952-090906c3-17e3-4e3e-838c-4d4a5e4af425.png">
