### ISSUE TITLE
real_prediction.npy

### ISSUE THREAD

**Issue by c1nc** [cure-lab/LTSF-Linear#22]
Thank you for publishing this paper! I am using **_DLinear_** model and the dataset is **_Weather_** data provided by you to predict Weather data. I'm a little confused about the content of **_real_prediction.npy_** . Could you plz explain how it relates to the real weather data? 

This is the part of **_real_prediction.npy_**(pred_len 192):
<img width="1329" alt="image" src="https://user-images.githubusercontent.com/34436486/195280102-1c0e065d-0874-4228-a688-60ce779fe2b8.png">

Scripts:
```
python -u run_longExp.py
 --is_training 1 
 --root_path ./dataset/ 
 --data_path weather.csv 
 --model_id weather_336_192 
 --model DLinear 
 --data custom 
 --features M 
 --seq_len 336
 --pred_len 192 
 --enc_in 21 
 --des 'Exp' 
 --itr 1 
 --batch_size 16  > logs/LongForecasting/DLinear_Weather_336_192.log
```

**Comment by mixiancmx** [comment]
This data is normalized, if you want to get the data in the original scale, you can modify lines 339-340 in exp_main by the following code:
<img width="468" alt="image" src="https://user-images.githubusercontent.com/83197963/195282677-e8937ab0-98e3-40eb-ad0b-a35b4f41925f.png">

**Comment by c1nc** [comment]
> This data is normalized, if you want to get the data in the original scale, you can modify lines 339-340 in exp_main by the following code: <img alt="image" width="380" src="https://user-images.githubusercontent.com/83197963/195282900-2fed1543-4181-4399-896a-aaaa3cb5bfd2.png">

Thank you very much!
