### ISSUE TITLE
hi, a quick question out IMS & DMS exp

### ISSUE THREAD

**Issue by immusferr** [cure-lab/LTSF-Linear#23]
Hello, have you ever tried any experiments on IMS tasks?   I'm curious about the performance of DLinear on IMS tasks.

**Comment by mixiancmx** [comment]
Hello! We didn't conduct experiments on IMS tasks. I think in IMS tasks, DLinear is quite similar to statistical methods -- It is a weighted sum of historical values, where weights are learned. 

Also, in IMS tasks, the predicted length is only 1. The number of parameters in DLinear will be extremely small (LookBackWindow*2). Therefore the capacity of DLinear might be too small.

**Comment by immusferr** [comment]
Thanks for your explanation and DLinear is indeed an outstanding work. However, i am looking for works testing on IMS tasks, could you like to recommend me some good works. Thanks :D .

**Comment by mixiancmx** [comment]
Maybe you can try another work from our lab -- SCINet. With an output length 1, it can be an IMS model. Also, you can try N-beats.
