### ISSUE TITLE
Table 9 Linear在ETTh1 dataset上pred_lens=96性能是否有问题？

### ISSUE THREAD

**Issue by iorange-1014** [cure-lab/LTSF-Linear#27]
Table 9 Linear在ETTh1 dataset上，直觉认为越长pred_lens模型性能应该越差，这样pred_lens=96性能是否有问题？
以下是我这边实现的结果：
ETTh1 dataset, seq_lens = 168, pred_lens = 96
DMS Linear mse=0.059, mae=0.180

**Comment by mixiancmx** [comment]
因为三个linear我都用一样的学习率和batch size跑，linear这个结果看着确实是有点拟合得不好，我之后会更新下表格
