### ISSUE TITLE
what's label_len in your code?

### ISSUE THREAD

**Issue by LiuHao-THU** [cure-lab/LTSF-Linear#29]
hello,
i found label_len in your code which is hard to understand, could you explain what's label_len in your code?

<img width="657" alt="Screenshot 2022-11-17 at 1 45 45 AM" src="https://user-images.githubusercontent.com/30975916/202254966-007ab547-1dae-4178-9532-ff02ede6b93d.png">

**Comment by mixiancmx** [comment]
Hi, this argument is used by transformer-based methods. The decoder of transformers also has an input sequence. Label length is the length of historical data in the input sequence.
