### ISSUE TITLE
关于训练数据量和时间特征对于linear模型的影响

### ISSUE THREAD

**Issue by stillwaterman** [cure-lab/LTSF-Linear#30]
您好，非常令人眼前一亮的工作。我看您在文章中分析了一下训练数据量对于一些former的影响，我想问一下训练数据量对于linea模型的影响您有大致分析过吗？另外，如果对linear模型结合一些时间特征time embedding（不采用informer的embedding方式），对模型性能会有什么样的影响呢

**Comment by mixiancmx** [comment]
训练数据量对于linea模型的影响：
相比transformer，linear对数据的需求会小一些。我将训练数据缩减到1% 5% 10%时，linear的performance drop会比transformers小很多。

Linear模型结合时间特征：
我尝试过直接将时间特征作为模型输入或将时间特征作为多变量预测中的一个通道，似乎对linear的学习都没有帮助。可能MoE，比如不同时间用不同的linear的做法比较合适。

**Comment by stillwaterman** [comment]
感谢您的回复，但我看文中训练数据量下降transformer的performance在某些情况下还会上升，linear模型确实更符合直觉。时间特征好像在transformer上也没什么作用。作为一种人为定义的周期概念（时间），好像确实不符合一些自然规律。

**Comment by mixiancmx** [comment]
因为数据集里通常有distribution shift，所以在数据充足的情况下，减少数据偶尔能带来提升

**Comment by stillwaterman** [comment]
@mixiancmx 好的，我理解了，持续关注您的工作。

**Comment by CK-TD** [comment]
> 训练数据量对于linea模型的影响： 相比transformer，linear对数据的需求会小一些。我将训练数据缩减到1% 5% 10%时，linear的performance drop会比transformers小很多。
> 
> Linear模型结合时间特征： 我尝试过直接将时间特征作为模型输入或将时间特征作为多变量预测中的一个通道，似乎对linear的学习都没有帮助。可能MoE，比如不同时间用不同的linear的做法比较合适。

您好 这里的 ‘训练数据缩减到1% 5% 10%’ 指的是相对于什么数据量？还有就是像原文中所用的预测长度，例如 T ∈ {96, 192, 336, 720}，这些长度相对原数据集中timesteps的总量都是非常小的，请问训练的数据和预测的数据是原数据集中的哪一部分呢？谢谢！
