### ISSUE TITLE
A small question about run Autoformer

### ISSUE THREAD

**Issue by ytzfhqs** [cure-lab/LTSF-Linear#32]
作者您好，我在跑Autoformer模型时出现错误（DLinear和NLinear模型能正常运行），Given groups=1, weight of size [512, 7, 3], expected input[32, 5, 482] to have 7 channels, but got 5 channels instead，请问是什么原因？

**Comment by ytzfhqs** [comment]
检查代码后发现是enc_in、dec_in、c_out参数为7，改成5以后代码正常运行了。我理解的这3个参数大小应该是数据除日期列的其他列列数，不知道是不是这样

**Comment by mixiancmx** [comment]
是的，这三个参数都跟数据的通道数有关
