### ISSUE TITLE
A question about reprocuctive results on ETT dataset

### ISSUE THREAD

**Issue by Jason7282** [cure-lab/LTSF-Linear#33]
作者您好，我在使用您提供的脚本的DLinear模型跑ETT集的时候，发现复现不了您论文的结果，然后我根据您的最新更新更改了seq_len=96，仍然是没能得到期望的结果，想请问一下，是否还有其他的超参需要设置？可否更新关于这个数据集的最新脚本呢？谢谢，期待您的回复。

**Comment by mixiancmx** [comment]
seq_len 336试过吗

**Comment by Jason7282** [comment]
您好，一开始用的是这个默认参数seq_len=336, 结果是pre_len越大的话和论文结果差距越明显。其他数据集的话基本是正常的。想问下论文结果是跑了多次取平均的吗？每次的波动大吗？谢谢

**Comment by Jason7282** [comment]
作者您好，感谢您的回复。我想问一下，在Table 2中，文章的方法使用seq_len=336和baselines方法的seq_len=96进行比较，如果baselines的方法也用336的话是不是效果也会好呢？还有在资源比较的Table 8中是否也需要用seq_len=336和其他方法的seq_len=96进行对比呢？期待您的回复，谢谢！

**Comment by mixiancmx** [comment]
复现的问题：我这边可以复现，我们论文里只跑了一个seed。复现结果不一致可能是因为设备或者torch的影响，你可以尝试下改改random seed或者简单的在你设备上试试不同batch size和lr，毕竟linear运行成本很小，可以写个script简单试试。（我近期也发现我在学校不同gpu上跑出来结果不一致）

Table2: 96是baseline方法最好的输入长度，你可以看看我们正文的figure4，补充材料的figure6，输入长度变长baseline反而变差。我们认为他们不能很好的利用到输入序列中的信息。

关于Table 8，你可以简单的把DLinear parameter 乘以3.5得到336输入下的parameters. 我们当时做实验是为了横行比较，所以用的一样的输入长度。

**Comment by Jason7282** [comment]
好的，非常感谢您的详细回复和您的impressive工作.
