### ISSUE TITLE
Cannot reproduce the paper results with the exchange_rate dataset

### ISSUE THREAD

**Issue by oguiza** [cure-lab/LTSF-Linear#39]
Hi,
I've used your scripts to try and reproduce the results of the exchange dataset but the results look different for some forecast horizons:

![Screen Shot 2023-01-19 at 20 09 55](https://user-images.githubusercontent.com/11656416/213537921-eaba4838-732d-4979-b22f-f5f6c7ea6ae9.png)

I wonder if you've made any changes to the code base after you run your experiments that might have had a negative impact on performance. 

The results I got are still better than for other Transformers, and very close to the published ones for "Repeat". If this is the case, it would indicate that none of the models in the study is capable of correctly predicting the exchange rate in the long term better than the last available value (which is not the case for other datasets).

**Comment by mixiancmx** [comment]
Yes, we deleted some unused layer and a weight initialization of DLinear model, but it doesn't affect the results in most dataset (I tested on a few datasets, and the results are almost the same as before). 

You can use the following model and the script to accurately reproduce the result in the table. The sequence length can be set to 336 or 96. 96 can achieve a better result. 336 can reproduce the result in the table.

1. Replace the DLinear.py with the following code (our first version of DLinear):
https://github.com/cure-lab/LTSF-Linear/blob/9d933a8050543eaf2074309145d7c9757d4833ec/models/DLinear.py

2. Use the following script:
python -u run_longExp.py \
  --is_training 1 \
  --root_path ./dataset/ \
  --data_path exchange_rate.csv \
  --model_id Exchange_96_720 \
  --model DLinear \
  --data custom \
  --features M \
  --seq_len 96 \
  --pred_len 720 \
  --enc_in 8 \
  --des 'Exp' \
  --itr 1 --batch_size 32 --learning_rate 0.005
 
3. The expected result is :
Sequence Length 96: <img width="567" alt="image" src="https://user-images.githubusercontent.com/83197963/213700256-21ac4f7d-40dc-4397-89ef-af4257dc1443.png">
Sequence Length 336: 
<img width="566" alt="image" src="https://user-images.githubusercontent.com/83197963/213700902-76ed9aa3-d738-450d-95c2-cf68a3f8ba1a.png">

**Comment by mixiancmx** [comment]
It is hard to predict exchange rate only based on historical value. You can also take a look at the weights of DLinear. It follows the trend of historical data to predict the future value, so it might be better than repeat sometimes.

**Comment by oguiza** [comment]
Thanks a lot, @mixiancmx  for your quick and clear response. I've been able to reproduce the results based on the code and command you have shared.
I agree with you that it's very difficult to predict the exchange rate. At least linear models are similar to random, unlike transformers that have worse performance.
