### ISSUE TITLE
output_attention参数意味着什么呢？

### ISSUE THREAD

**Issue by chendingyan** [cure-lab/LTSF-Linear#40]
在阅读代码的过程中没太搞懂output_attention参数的意思，看代码是仅仅有transformer-based method 用到了这个参数？

**Comment by chendingyan** [comment]
另外还有一个问题，如果仅仅看DLinear/NLinear的实现代码的话，timestamp类型特征的解析出来的 batch_x_mark,batch_y_mark 是不是也没有用到呢？

**Comment by mixiancmx** [comment]
> 

对的，具体意思要看他们模型里怎么用的
