### ISSUE TITLE
关于MS multivariate predict univariate

### ISSUE THREAD

**Issue by chendingyan** [cure-lab/LTSF-Linear#41]
参数features type如果选择MS的话，应该是multivariate predict univariate，那么在这种情况下，看起来训练用到了 历史数据的各种多变量features，例如ETT数据集里的['HUFL', 'HULL','MUFL', 'MULL','LUFL','LULL'] 这些， 但inference/predict部分的时候并没有用到pred_features里的这些特征，而是直接预测了target，请问这个理解是不是正确的呢？

**Comment by mixiancmx** [comment]
是的，在我们这个repo里，MS是指用历史的数据的多通道预测未来的单通道，pred_features里的这些特征没有用到

**Comment by chendingyan** [comment]
那请问有没有考虑到多条长时间序列如何进行预测呢

**Comment by mixiancmx** [comment]
features type默认参数M就是多序列预测多序列
