### ISSUE TITLE
FEDformer

### ISSUE THREAD

**Issue by mieya** [cure-lab/LTSF-Linear#45]
It seems like there are some spelling errors in FEDformer/scripts/LongForecasting.sh.
![77c949c5e62dd05ebe7dc99876a80a8](https://user-images.githubusercontent.com/46099716/219996906-b9ceb216-f096-4f40-a967-964e261dbe88.png)
preLen should be change to pred_len.

**Comment by mixiancmx** [comment]
I think it is not a spelling error. "preLen" is the variable name we define in line 10. "pred_len" is the argument of run.py.
