### ISSUE TITLE
Question about short-time prediction

### ISSUE THREAD

**Issue by christincha** [cure-lab/LTSF-Linear#49]
Dear author, 
thanks for the clear documentation!
Very great work.

I am curious how the model performs on the short-term prediction. Did you do some experiments on short-term prediction as shown in SCINet?
As shown in Fig.4 (effect of the feedback window size), when the look-back window size is small the Linear model performs worse than some transformer models. Do you have any intuitive interpretation of this?

Best,

**Comment by mixiancmx** [comment]
No, we don't formally conduct experiments on short-term forecasting. But I remember I have tried before, and the performance is not as good as SCINet. The main reason is that the number of parameters of the Linear layer is input length * predicted length. If the predicted length is 3 (short-term), the capacity of the Linear model is extremely small.

**Comment by mixiancmx** [comment]
Another reason that linear can not perform well in short-term forecasting is that it doesn't explicitly consider the relation of different channels (for example, traffic data).

**Comment by christincha** [comment]
Thanks! This makes a lot of sense.
