### ISSUE TITLE
关于MS

### ISSUE THREAD

**Issue by luoxia-wen** [cure-lab/LTSF-Linear#51]
您好，请问在代码中，如果设置individual为True的情况下，MS是否与S没有区别，MS只是**分别**计算了N个变量的结果，然后输出了target的结果？

**Comment by mixiancmx** [comment]
对的，Linear模型没有考虑变量的关系，所以individual+MS和S没区别

**Comment by rdyan0053** [comment]
我的理解是：
当feature参数设置为S：以ETTh1数据集为例，有效输入就是OT的历史数据，经过Linear模型，输出就是OT的预测数据
当feature参数设置MS，individual为True时：还以ETTh数据集为例，有效输入是OT等7个维度的历史数据，经过Linear模型，输入的就是OT等7个维度的历史数据。但是因为各个维度的数据使用不同的Linear层来训练，参数不共享，所以本质上individual+MS和S没区别

请问我这个理解对吗
