### ISSUE TITLE
start a new process before the current process

### ISSUE THREAD

**Issue by Aliweka2020** [cure-lab/LTSF-Linear#52]
when I run the existing training command 
sh scripts/EXP-LongForecasting/Linear/exchange_rate.sh
I get this error. I am using anaconda windows environment   

An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

**Comment by Aliweka2020** [comment]
this thread solve the problem
https://github.com/cure-lab/LTSF-Linear/issues/38

**Comment by mixiancmx** [comment]
Thanks
