### ISSUE TITLE
comparison of results 

### ISSUE THREAD

**Issue by ramankhurana** [cure-lab/LTSF-Linear#54]
Nice package and comparison results shown in paper. I have two issue in understanding of the results when running for DLinear. 

1. Is there any description about what does result.npy store, it seems to have a lumpy array with three dimension, but I was expecting it to be 2d only, e.g. when predicting for next 96 timestamps for exchange.csv I would expect shape of lumpy array to be ( 96, 8)however I get (1416, 96, 8). I wonder if I am missing something in the inferencing part or how is it working? 

2. Is there an existing macro, script to make the table shown in paper, or a function which calculate the metric using the results.npy and using ground truth.

**Comment by mixiancmx** [comment]
Q2:
You can uncomment line 304, then the program will also save the ground truths. Use the function in utils.metrics.py, you can get the metric. You can follow what we do in line 293.

<img width="804" alt="image" src="https://user-images.githubusercontent.com/83197963/223304347-2ebe051b-a33e-4023-9b0f-a169100184a1.png">

**Comment by ramankhurana** [comment]
> 

Thank you for replying, For Question 2 it is clear but for first one it is still not clear. Please see the followup, 

yes I meant pred.npy. I don't understand what do you mean by there are more than one sequence in the dataset? Do you mean there are 1416 datasets categories (multivariate time series) and each of them have 8 time series? 

In that case it is not clear which variable is being used to categorize the dataset into 1416 categories. Sorry if the question is naive and I am missing something very intuitive. 

Thanks again.

**Comment by mixiancmx** [comment]
For example, a dataset is (10000,8), which means it has the data for 10000 time stamps and 8 channels. Then we split it to train, valid, test. The test part is the (8000~10000, 8). Because the output of the model is 96, the number of test samples is roughly 2000-96=1904. Each test sample has an input sequence and an output sequence. For example, the first test samples use (8000-input length ~ 8000, 8) as input, and (8000~8096, 8) as output. The second one use (8001-input length ~ 8001, 8) as input, and (8001~8097, 8) as output

**Comment by ramankhurana** [comment]
Thanks for clearing it further, I understand but for the use case I am checking, exchange data, and forecasting for next 96 timestamps. How shape of the predicted array is three dimensional. 

I would expect array of shape (96,8) but I get 1416 such arrays. 

>>> a=np.load("results/Exchange_336_96_DLinear_custom_ftM_sl336_ll48_pl96_dm512_nh8_el2_dl1_df2048_fc1_ebtimeF_dtTrue_Exp_0/pred.npy")
>>> a.shape
(1416, 96, 8)

**Comment by mixiancmx** [comment]
Because the program save the outputs of all test samples in the test set.1416 is the number of test samples.

**Comment by ramankhurana** [comment]
Thanks I understood the way output is formatted.

**Comment by ramankhurana** [comment]
I closed this issue but realized a new problem popped up. I describe here: 
now I am running for ETTh1.csv as dataset for multivariate case. When I check the result.txt it shows 

<img width="1268" alt="image" src="https://user-images.githubusercontent.com/4996609/223515040-625f696a-ad93-4757-b0ed-a19ddd2b725b.png">

Two questions/doubts: 
1. The MSE value shown in the file is 0.384 but the difference in the time series sequence when compared to test series seems to be of very different size, e.g. in the image you can see last few values and their size, 

<img width="922" alt="image" src="https://user-images.githubusercontent.com/4996609/223516338-7cb1cb24-1515-4438-bafe-8a0082de7669.png">

However when you compare it with the pred.npy you will notice the values are very different. 

<img width="1184" alt="image" src="https://user-images.githubusercontent.com/4996609/223514933-01c09ed2-edee-4abc-bae0-3dd2e59469ca.png">

is the something still wrong in my understanding? 

2. In the result.txt I can see a list of numbers (of size 0.2..) in addition to MSE, can you please tell me what is this list? 
Thanks a lot for all the explanations.

**Comment by mixiancmx** [comment]
For Q1, this is because the results we save are the value after normalization. You need to denorm them before compare with the value in csv file

**Comment by mixiancmx** [comment]
Q2, that is the correlation value. For the computation of correlation, you can refer to file `utils/metrics.py`

**Comment by ramankhurana** [comment]
Thanks for all the explanation. I have got another question about the model. I have not managed to understand from the text if the weight matrix is same for all the variates of a multivariate dataset or they are different for each variate? Thanks again.

**Comment by mixiancmx** [comment]
Hello,  it is same for all the variates

**Comment by ramankhurana** [comment]
Thank you for clarification.
