### ISSUE TITLE
scripts/EXP-LongForecasting/Stat_Long.sh is not executable

### ISSUE THREAD

**Issue by xiao-he** [cure-lab/LTSF-Linear#55]
Firstly, line 5 of run_stat.py is 

    from exp.exp_naive import Exp_Main 

which may be 

    from exp.exp_stat import Exp_Main

Even I use exp_stat, there is still errors about input argument, like 

    timeenc = 0 if args.embed != 'timeF' else 1
AttributeError: 'Namespace' object has no attribute 'embed'

**Comment by mixiancmx** [comment]
It is fixed now. (I don't carefully check the implementation in stats_model. It is not used in our paper except "repeat)
