### ISSUE TITLE
Why the model is not working with different seq_len and pred_len?

### ISSUE THREAD

**Issue by tanwimallick** [cure-lab/LTSF-Linear#57]
python -u run_longExp.py --is_training 1 --root_path dataset/  --data_path electricity.csv --model_id sim_new --model NLinear --data custom --features M --seq_len 6 --pred_len 6 --enc_in 321 --des 'Exp' --itr 1 --batch_size 16 --learning_rate 0.005

Giving me error 
RuntimeError: stack expects each tensor to be equal size, but got [0, 321] at entry 0 and [54, 321] at entry 1

**Comment by mixiancmx** [comment]
You need to set a label length that is lower than the sequence length. For example, add --label_len 1 or --label_len 0, then the script can work

**Comment by tanwimallick** [comment]
What is label length?

**Comment by mixiancmx** [comment]
It is a parameter used by Transformer methods.

**Comment by tanwimallick** [comment]
I understand that. I was asking what it meant in the context of the seq_len and pred_len.
