### ISSUE TITLE
线程报错/tuple index out of range

### ISSUE THREAD

**Issue by zhangdongliang123-tyut** [cure-lab/LTSF-Linear#59]
作者您好！非常佩服你们的工作，我在时序数据预测上是新手，在运行exchange_rate.sh时报错线程有冲突，一个线程未关闭又开启了新线程，于是我将 run_longExp.py 中第64行“--num_workers”默认值设为0，train正常早停，但是在test时，exp/exp_main.py 第284行preds.shape[-2] 报错 tuple index out of range，查看此时preds的shape为（178，）于是我把preds.shape[-2]删掉可以继续运行一段，在计算MAE时报错：ValueError: operands could not be broadcast together with shapes (8,96,8) (6,96,8)  而我查看preps[0].shape 和truest[0].shape 是相等的，皆为(8,96,8) ，请问我那里出错了导致无法正确运行本代码呢？还请您不吝赐教

**Comment by mixiancmx** [comment]
不好意思，前两天有个issue让我把drop_last改成false，这个bug是因为改完后你所说的保存那里维度对不上了
我刚更新了下代码，按道理是能运行了，你方便再试试嘛，如果还不行可以先在data_factory.py把测试时 drop_last 改回True

**Comment by zhangdongliang123-tyut** [comment]
确实可以运行了，感谢修复！继续拜读

**Comment by zhandsom** [comment]
> 作者您好！非常佩服你们的工作，我在时序数据预测上是新手，在运行exchange_rate.sh时报错线程有冲突，一个线程未关闭又开启了新线程，于是我将 run_longExp.py 中第64行“--num_workers”默认值设为0，train正常早停，但是在test时，exp/exp_main.py 第284行preds.shape[-2] 报错 tuple index out of range，查看此时preds的shape为（178，）于是我把preds.shape[-2]删掉可以继续运行一段，在计算MAE时报错：ValueError: operands could not be broadcast together with shapes (8,96,8) (6,96,8) 而我查看preps[0].shape 和truest[0].shape 是相等的，皆为(8,96,8) ，请问我那里出错了导致无法正确运行本代码呢？还请您不吝赐教

**Comment by zhandsom** [comment]
哥们，我也报了这个错，在data_factory.py把测试时 drop_last 改回True还是报错了，不知道你是如何解决的。还望不吝赐教
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

**Comment by fengqsam** [comment]
> 

我在debug test任务的时候，执行for i, (batch_x, batch_y, batch_x_mark, batch_y_mark) in enumerate(test_loader):的时候也遇到这个错误，好奇怪

**Comment by fengqsam** [comment]
> 哥们，我也报了这个错，在data_factory.py把测试时 drop_last 改回True还是报错了，不知道你是如何解决的。还望不吝赐教 RuntimeError: An attempt has been made to start a new process before the current process has finished its bootstrapping phase.
> 
> ```
>     This probably means that you are not using fork to start your
>     child processes and you have forgotten to use the proper idiom
>     in the main module:
> 
>         if __name__ == '__main__':
>             freeze_support()
>             ...
> 
>     The "freeze_support()" line can be omitted if the program
>     is not going to be frozen to produce an executable.
> ```

我在run.py里面加上if __name__ == '__main__':能把这个问题解决
<img width="493" alt="1694269663841" src="https://github.com/cure-lab/LTSF-Linear/assets/17719434/b7b7357f-0942-4b12-b537-e1b5b704773a">

**Comment by zhandsom** [comment]
哥们，加个微信交流一下不？15597887673



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月9日(周六) 晚上10:28
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [cure-lab/LTSF-Linear] 线程报错/tuple index out of range (Issue #59)




  
哥们，我也报了这个错，在data_factory.py把测试时 drop_last 改回True还是报错了，不知道你是如何解决的。还望不吝赐教 RuntimeError: An attempt has been made to start a new process before the current process has finished its bootstrapping phase.
     This probably means that you are not using fork to start your     child processes and you have forgotten to use the proper idiom     in the main module:         if __name__ == '__main__':             freeze_support()             ...     The "freeze_support()" line can be omitted if the program     is not going to be frozen to produce an executable.   
我在run.py里面加上if name == 'main':能把这个问题解决
