### ISSUE TITLE
关于--model_id

### ISSUE THREAD

**Issue by Ouyyyu** [cure-lab/LTSF-Linear#60]
parser.add_argument('--model_id', type=str, required=True, default='test', help='model id')
这行代码中的--model_id在后面是不是没有用到？

**Comment by mixiancmx** [comment]
用在保存模型，预测结果的文件名

**Comment by mixiancmx** [comment]
我猜是没有读到数据集？

**Comment by Ouyyyu** [comment]
> 

应该不是这个问题 数据集读取我已经解决完了

**Comment by Ouyyyu** [comment]
![image](https://user-images.githubusercontent.com/103258786/226572440-5f57fea6-9a6c-4f0b-9c47-54d568587ff8.png)
似乎是val数据集读取的问题  但train数据集就没有问题啊
