### ISSUE TITLE
normalization of the inputs 

### ISSUE THREAD

**Issue by ramankhurana** [cure-lab/LTSF-Linear#64]
I see that the inputs are normalized using StandardScaler. Do I understand correct that MSE and other metrics are calculated, i.e. the numbers quoted in the table and paper for various dataset are after scaling, not the actual numbers, correct?

**Comment by ailingzengzzz** [comment]
Hi @ramankhurana,

Yes, we report the normalized errors following previous works to have a fair quantitative comparison. Actually, reporting the normalized errors can also provide additional observations in future work.
