### ISSUE TITLE
关于Informer模型的问题

### ISSUE THREAD

**Issue by chendingyan** [cure-lab/LTSF-Linear#65]
为什么在模型训练的时候 对于informer类型的模型 在Exp_main.py的163行（https://github.com/cure-lab/LTSF-Linear/blob/main/exp/exp_main.py#L163）
outputs = self.model(batch_x, batch_x_mark, dec_inp, batch_y_mark, batch_y)
正常不应该是
outputs = self.model(batch_x, batch_x_mark, dec_inp, batch_y_mark) 就行吗

**Comment by mixiancmx** [comment]
这个应该是训练时对应模型输入里的enc_self_mask，测试时是没有使用的
