### ISSUE TITLE
where to download exchange_rate.csv?

### ISSUE THREAD

**Issue by mw66** [cure-lab/LTSF-Linear#67]
https://github.com/laiguokun/multivariate-time-series-data

only have exchange_rate.txt.gz, without any header I symlink it as exchange_rate.csv, but I got error:

```
...
/LTSF-Linear/data_provider/data_loader.py", line 233, in __read_data__
    cols.remove('date')
ValueError: list.remove(x): x not in list
```

**Comment by mixiancmx** [comment]
I still can find exchange_rate.csv in the link. 
<img width="531" alt="image" src="https://user-images.githubusercontent.com/83197963/232337118-5e4d63d9-d6f1-4e84-a110-dd5adebaa30e.png">

**Comment by mw66** [comment]
https://drive.google.com/drive/mobile/folders/1ZOYpTUa82_jCcxIdTmyr0LXQfvaM9vIy

OK, I see
