### ISSUE TITLE
关于数据长度

### ISSUE THREAD

**Issue by SimyokH** [cure-lab/LTSF-Linear#69]
尊敬的作者您好，打扰您宝贵的时间，有一些问题想请教您~
在做自己的测试的时候发现数据集长短不一致，即:我用的数据实际长度为25842，划分方式仍为721，seq:lab:pred=336:336:720。但是运行面板显示我的train+val+test为23349（开启了do_predict），那少掉的这一部分数据去哪儿了呢？
感谢您的解答！

**Comment by mixiancmx** [comment]
<img width="722" alt="image" src="https://user-images.githubusercontent.com/83197963/235295358-7802ade7-acb3-40f6-8cd0-e8804165ab91.png">
<img width="523" alt="image" src="https://user-images.githubusercontent.com/83197963/235295264-375a0328-16fa-4d94-8127-7770a3c45c3c.png">
这里计算应该是因为打印出的每个数据集长度都需要减去输入输出长度
