### ISSUE TITLE
Misplace benchmark for NLinear and DLinear compared to paper.

### ISSUE THREAD

**Issue by ginofft** [cure-lab/LTSF-Linear#70]
The values found in the benchmark (https://github.com/cure-lab/LTSF-Linear/blob/main/LTSF-Benchmark.md) differ from the value from the paper (https://arxiv.org/pdf/2205.13504.pdf)

Seem like the data rows for DLinear and NLinear were switched.

**Comment by Arslan-Mehmood1** [comment]
Right, I have another question regarding the training of linear model, may I ask?

**Comment by mixiancmx** [comment]
> The values found in the benchmark (https://github.com/cure-lab/LTSF-Linear/blob/main/LTSF-Benchmark.md) differ from the value from the paper (https://arxiv.org/pdf/2205.13504.pdf)
> 
> Seem like the data rows for DLinear and NLinear were switched.

Thanks, it is fixed now.

**Comment by mixiancmx** [comment]
> Right, I have another question regarding the training of linear model, may I ask?

sure

**Comment by Arslan-Mehmood1** [comment]
@mixiancmx  sir, in training using run_longexp.py, the freq parameter has no effect on the results, I got same results by freq='5h', freq='h', freq='5min' on ADAUSDT dataset which has time index of 5min. Please if you could guide and provide any explanation!

![image](https://user-images.githubusercontent.com/51626734/235295325-23911357-ca17-4de1-9ed0-0bdb59f8c525.png)

**Comment by iganggang** [comment]
It seems that the author did not reply you.
