### ISSUE TITLE
关于log的生成

### ISSUE THREAD

**Issue by rookieonebin** [cure-lab/LTSF-Linear#72]
尊敬的作者您好，打扰了，有一些问题想请教您~
关于log的生成，在运行完一次scripts/中的文件后项目文件夹会生成log，但我阅读了整个项目以后并没有阅读到关于生成 .log文件这部分的代码。只有在shell脚本里有生成文件夹的代码。 如：
if [ ! -d "./logs" ]; then
    mkdir ./logs
fi
if [ ! -d "./logs/LongForecasting" ]; then
    mkdir ./logs/LongForecasting
fi
另外在script/ 里的shell脚本里有  类似： --itr 1  >logs/LongForecasting/$model_name'_Etth1_'$pred_len.log 的一行设置了.log文件名， 但在ArgumentParser() 对象里我也没有阅读到相关参数。
所以想请教下.log文件是如何生成的以及相关代码的位置，非常感谢！

**Comment by NotF404** [comment]
就是通过shell脚本中 ”>“ 符号指定输出的log路径。 实际是把print到terminal中所有的输出转为输出到对于的log文件。
