### ISSUE TITLE
关于结果

### ISSUE THREAD

**Issue by SimyokH** [cure-lab/LTSF-Linear#74]
尊敬的作者您好，感谢您之前对我提出的问题的耐心解答，在进一步了解后我复现关于WTH，参数与脚本内容相同的情况下得到如下结果，想请教您该怎么调参，或者您可以展示一下您当时预测结果的对比图吗？十分感激！
![image](https://github.com/cure-lab/LTSF-Linear/assets/120697840/33ae8e40-131d-4514-9177-98ec6624a878)

**Comment by SimyokH** [comment]
seq：lab：pre_lenth ----96:48:48

**Comment by mixiancmx** [comment]
这是哪个模型呀，一般linear的话输入长度可以拉长一点比如336。其他模型的话可以就改改batch size 和lr试试吧
