### ISSUE TITLE
LogTrans Implementation

### ISSUE THREAD

**Issue by linfeng-du** [cure-lab/LTSF-Linear#75]
Dear Authors,
Thank you for your great work and sharing the well-sorted codebase!
Regarding LogTrans, it seems that the authors didn't release their offical codes. Would like to know what implementation did you use and whether are you planning to release the implementation.

Thanks.

**Comment by mixiancmx** [comment]
Sorry, we did not implement LogTrans. The result of that model is copied from Fedformer paper and Autoformer paper.
