### ISSUE TITLE
结果复现不一致

### ISSUE THREAD

**Issue by Chenyue2436** [cure-lab/LTSF-Linear#76]
我按照您提供的github代码、环境和scripts进行了复现，但发现DLinear的结果与您在论文上贴出的多变量结果不一致，尤其是在ETTh数据集上，请问我是有遗漏掉什么吗？
期待得到您的答复~

**Comment by mixiancmx** [comment]
我们后续对模型做了一点更改，比如把loader的drop last改成了false，统一了几个linear模型的超参。如果你想要复现与文中完全一致的DLinear结果的话，可以考虑查看我们最早的一版，历史提交里应该可以找到。正常是可以完全复现出一样的值的

**Comment by Chenyue2436** [comment]
非常感谢您百忙之中能抽空回复，我会按照您提出的建议去尝试一下，再次感谢您~




陈越
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cure-lab/LTSF-Linear"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月18日(星期四) 下午3:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cure-lab/LTSF-Linear] 结果复现不一致 (Issue #76)





 
我们后续对模型做了一点更改，比如把loader的drop last改成了false，统一了几个linear模型的超参。如果你想要复现与文中完全一致的DLinear结果的话，可以考虑查看我们最早的一版，历史提交里应该可以找到。正常是可以完全复现出一样的值的

**Comment by xiongqi111** [comment]
您好，请问根据作者的回复，最后实验能够复现论文效果吗？我参照first upload的设置，还是没有获得良好的结果

**Comment by Chenyue2436** [comment]
我没有进一步尝试了，的确难以复现论文的结果。



---原始邮件---
发件人: "Xiong ***@***.***&gt;
发送时间: 2023年10月11日(周三) 下午4:34
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [cure-lab/LTSF-Linear] 结果复现不一致 (Issue #76)




 
您好，请问根据作者的回复，最后实验能够复现论文效果吗？我参照first upload的设置，还是没有获得良好的结果

**Comment by xiongqi111** [comment]
好的，感谢



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年10月11日 16:45 |
| 收件人 | ***@***.***> |
| 抄送至 | Xiong ***@***.***>***@***.***> |
| 主题 | Re: [cure-lab/LTSF-Linear] 结果复现不一致 (Issue #76) |

我没有进一步尝试了，的确难以复现论文的结果。



---原始邮件---
发件人: "Xiong ***@***.***&gt;
发送时间: 2023年10月11日(周三) 下午4:34
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [cure-lab/LTSF-Linear] 结果复现不一致 (Issue #76)





您好，请问根据作者的回复，最后实验能够复现论文效果吗？我参照first upload的设置，还是没有获得良好的结果

**Comment by iganggang** [comment]
我也复现不出结果，怎么办？我用cuda11.5和cuda12.1结果一样
