### ISSUE TITLE
Issue running experiments with Naive model

### ISSUE THREAD

**Issue by wellisonraul** [cure-lab/LTSF-Linear#78]
Dear developers,

I am experiencing difficulties replicating the Repeat (Naive) experiments. Whenever I try to run the experiments, the following messages pop up:

 **File "run_stat.py", line 65, in <module>
    exp.test(setting)
  File "/LTSF-Linear/exp/exp_stat.py", line 85, in test
    preds = preds.reshape(-1, preds.shape[-2], preds.shape[-1])
IndexError: tuple index out of range**

Are there any updates that caused the scripts to malfunction?

I ran the file: **LTSF-Linear/scripts/EXP-LongForecasting/Stat_Long.sh**. I followed the installation guide in the README and installed tqdm and pmdarima to run the script.

Thank you for your help.

**Comment by mixiancmx** [comment]
Sorry, we forget to update exp_stat.py after updating the data factory. Now it is fixed. Thanks for pointing out this.
