### ISSUE TITLE
DLinear如何进行反归一化

### ISSUE THREAD

**Issue by wenrutong** [cure-lab/LTSF-Linear#79]
DLinear如何进行反归一化，不算太熟悉

**Comment by wenrutong** [comment]
是test保存文件的时候，进行反归一化。有点懵逼

**Comment by mixiancmx** [comment]
在exp_main的284行插入 “xx = test_data.inverse_transform(xx)”，xx是你要反归一化的东西

**Comment by mixiancmx** [comment]
这是data set里的这个函数
<img width="474" alt="image" src="https://github.com/cure-lab/LTSF-Linear/assets/83197963/6acca83c-e6ee-41c1-ba2e-5c93be6ee759">

**Comment by wenrutong** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年6月5日(星期一) 中午12:12
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [cure-lab/LTSF-Linear] DLinear如何进行反归一化 (Issue #79)





 
在exp_main的284行插入 “xx = test_data.inverse_transform(xx)”，xx是你要反归一化的东西

**Comment by wenrutong** [comment]
谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年6月5日(星期一) 中午12:13
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [cure-lab/LTSF-Linear] DLinear如何进行反归一化 (Issue #79)





 
这是data set里的这个函数

**Comment by yanshuaibupt** [comment]
维度还需要从3维变成2维
