### ISSUE TITLE
Pre-processing of electricity.csv?

### ISSUE THREAD

**Issue by Mark-Lowell** [cure-lab/LTSF-Linear#80]
Hi! I'm trying to replicate the results in your paper, and I'm a bit confused about the electricity.csv file. According to footnote 4 on page 9 of the paper, this data was obtained from:

https://archive.ics.uci.edu/ml/datasets/ElectricityLoadDiagrams20112014

However, the data at that link runs from 2011 to 2014. The data in the electricity.csv file runs from 2016 to 2019. Is this the same data?

**Comment by mixiancmx** [comment]
I am sorry about the confusing footnote. In fact, we follow other works and use that link as the reference of electricity.csv. The data we use is the one that runs from 2016 to 2019.
