### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by Med-Rokaimi** [cure-lab/LTSF-Linear#83]
I'm trying to run DLinear on a custom dataset via Google Colab notebook.
I added this lines to initialize the settings args:
`
args = dotdict()
args.target = 'Price'
args.des = 'test'
args.dropout = 0.05
args.num_workers = 10
args.gpu = 0
args.devices = '0'
args.use_gpu = True
args.use_multi_gpu = False
args.freq = 'd'
args.is_trainging = 1
#args.root_path = './dataset/'
args.data_path ='oil.csv' 
#args.model_id='oil_14_2xx'
args.model = 'DLinear'
args.data = 'oil'
args.features = 'MS'
args.seq_len = 22
args.label_len = 11
args.pred_len = 2
args.e_layers = 2
args.d_layers = 1
args.n_heads = 8
args.factor = 3
args.enc_in = 4
args.dec_in =4
args.c_out = 1
args.d_model = 512
args.des = 'Exp'
args.itr = 1
args.d_ff = 2048
args.moving_avg = 45
args.factor = 1
args.distil = True
args.output_attention = False
args.patience= 4
args.learning_rate = 0.0001
args.batch_size = 1 
#args.embed = 'timeF'
args.activation = 'gelu'
args.use_amp = False
args.loss = 'mse'
args.train_epochs = 4
`
I got this error message:
Use CPU
>>>>>>>start training : None_DLinear_oil_ftMS_sl22_ll11_pl2_dm512_nh8_el2_dl1_df2048_fc1_ebNone_dtTrue_Exp_0>>>>>>>>>>>>>>>>>>>>>>>>>>
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-6-766ebf4895f4>](https://localhost:8080/#) in <cell line: 3>()
     24         exp = Exp(args)  # set experiments
     25         print('>>>>>>>start training : {}>>>>>>>>>>>>>>>>>>>>>>>>>>'.format(setting))
---> 26         exp.train(setting)
     27 
     28         if not args.train_only:
5 frames
[/usr/lib/python3.10/posixpath.py](https://localhost:8080/#) in join(a, *p)
     74     will be discarded.  An empty last part will result in a path that
     75     ends with a separator."""
---> 76     a = os.fspath(a)
     77     sep = _get_sep(a)
     78     path = a

TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by mixiancmx** [comment]
This might because of missing dataset file.
