### ISSUE TITLE
Confusion regarding the indexing of data labels!!!!!

### ISSUE THREAD

**Issue by XZXSean** [cure-lab/LTSF-Linear#85]
for any train data item, in your 'data_loader.py' ,the code is :

```python
        s_begin = index
        s_end = s_begin + self.seq_len
        r_begin = s_end - self.label_len
        r_end = r_begin + self.label_len + self.pred_len

        seq_x = self.data_x[s_begin:s_end]
        seq_y = self.data_y[r_begin:r_begin + self.label_len]
        seq_x_mark = self.data_stamp[s_begin:s_end]
        seq_y_mark = self.data_stamp[r_begin:r_end]
``` 

> why the 'seq_y' is end with **_'r_begin + self.label_len_**'? rather than **' s_begin + self.seq_len+self.pred_len '**

the data begin from 'r_begin ' and end with 'r_begin + self.label_len' **are all located in the history sequence**.

**I fell puzzled for this.**

the same code in Autoformer is 'seq_y = self.data_y[r_begin:r_end]'

**Is this an error or is it supposed to be like this?**

I am looking forward to your response.

best wishes

**Comment by mixiancmx** [comment]
This code is from `class Dataset_Pred(Dataset):`, where no ground truth value is available. Therefore the seq_y is not used, and the value of it has no meaning.  The other `class Dataset_` is 'seq_y = self.data_y[r_begin:r_end]', same as Autoformer.
