### ISSUE TITLE
【Look-back window size in LongForecast task】 and 【Accumulative error】

### ISSUE THREAD

**Issue by CXL-edu** [cure-lab/LTSF-Linear#86]
1. The file `Formers_Long.sh` and `Linear-l.sh` in the path `scripts/EXP_LongForecasting`. Why use different look-back window when comparing the effects of the same predicted length? According to the settings in the code, DLiner uses the previous 336 steps as input, while the transformer class only uses 96 steps as input.
2. In Figure. 4 also mentions the use of different look-back window on traffic and electricity dataset, respectively. Why do you want to do this? In addition, as the prediction step becomes longer and longer, why does the Mean squared error of prediction decrease instead of increasing?

1. 在`scripts/EXP_LongForecasting`文件夹下的`Formers_Long.sh` 和`Linear-l.sh` 文件中，为什么对比同样预测长度的效果，却使用不同的look-back窗口？按代码中的设置，DLinear使用之前的336步作为输入，而former类仅使用96步作为输入。
2. 在Figure. 4的图名中也提到分别在traffic和electricity上使用了不同的look-back window，请问为什么要这样做？此外随着预测步长越来越长，为什么预测的均方误差不增加反而减小了？

**Comment by mixiancmx** [comment]
诶这是中英文的吧，1和3看着一样。
其实我们文中figure4相关的那一个章节有讨论上述问题，您可以参考下。简单来说，look-back窗口在时序预测任务中是一个超参，还有很多文章使用其他的输入长度。其次，transformer在长的输入长度下并没有预测效果越来越好，96的输入长度反而是适合transformer的一个输入长度，这可能是因为他们没有办法很好的提取长输入的信息。相反，linear模型输入长度越长效果越好。
