### ISSUE TITLE
how to set the `enc_in` in DLinear?

### ISSUE THREAD

**Issue by rdyan0053** [cure-lab/LTSF-Linear#92]
Isn't the `enc_in` parameter specific to the Formers model? Why is this parameter also utilized in the DLinear model?
enc_in参数不是Formers模型中的参数吗？为什么在DLinear模型中也用到了这个参数？

**Comment by mixiancmx** [comment]
因为我们选项-i是 一个通道一个linear模型，在-i的情况下我复用了enc_in作为通道数
