### ISSUE TITLE
关于Stat_model是否能放在GPU运行的问题

### ISSUE THREAD

**Issue by fengqsam** [cure-lab/LTSF-Linear#93]
你好，请问您是否有试过将Stat_model放在GPU运行呢？在CPU运行的话比较慢，我尝试过将batch_x, batch_y放在GPU，但实际上Stat_model还是在CPU中运行

**Comment by mixiancmx** [comment]
不行哦，我们用的统计方式都是用的cpu库，好像都不支持gpu
